excerpt_separator: ""
markdown: kramdown
url: http://revati.github.io
title: revati
email: roberts@rego.lv
author: Roberts Guļāns
description: my thoughts about stuff
paginate: 3
google_analytics: 
